services:
  postgres:
    build: ./db
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: java_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
    ports:
      - "8080:8080"

  frontend:
      build: ./frontend
      container_name: nginx_frontend
      restart: always
      ports:
        - "3000:80"

volumes:
  postgres_data:
    driver: local
